
package br.com.redhat.service.corp.protocolo;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b14002 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "WSGerarProtocolo", targetNamespace = "http://service.anbima.com.br/corp/protocolo")
public interface ServicoProtocolo {

    /**
     * 
     * @param tipoProtocolo
     * @param origemProtocolo
     * @return returns br.com.anbima.service.corp.protocolo.Protocolo
     */
    @WebMethod
    @WebResult(name = "protocoloResponse", targetNamespace = "")
    @RequestWrapper(localName = "gerarProtocolo", targetNamespace = "http://service.anbima.com.br/corp/protocolo", className = "br.com.anbima.service.corp.protocolo.GerarProtocolo")
    @ResponseWrapper(localName = "gerarProtocoloResponse", targetNamespace = "http://service.anbima.com.br/corp/protocolo", className = "br.com.anbima.service.corp.protocolo.GerarProtocoloResponse")
    @Action(input = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarProtocoloRequest", output = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarProtocoloResponse")
    public Protocolo gerarProtocolo(@WebParam(name = "tipoProtocolo", targetNamespace = "") String tipoProtocolo,
	    @WebParam(name = "origemProtocolo", targetNamespace = "") String origemProtocolo);

    /**
     * 
     * @param tipoProtocolo
     * @param origemProtocolo
     * @param quantidade
     * @return returns
     *         java.util.List<br.com.anbima.service.corp.protocolo.Protocolo>
     */
    @WebMethod
    @WebResult(name = "listaProtocoloResponse", targetNamespace = "")
    @RequestWrapper(localName = "gerarListaProtocolos", targetNamespace = "http://service.anbima.com.br/corp/protocolo", className = "br.com.anbima.service.corp.protocolo.GerarListaProtocolos")
    @ResponseWrapper(localName = "gerarListaProtocolosResponse", targetNamespace = "http://service.anbima.com.br/corp/protocolo", className = "br.com.anbima.service.corp.protocolo.GerarListaProtocolosResponse")
    @Action(input = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarListaProtocolosRequest", output = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarListaProtocolosResponse")
    public List<Protocolo> gerarListaProtocolos(
	    @WebParam(name = "tipoProtocolo", targetNamespace = "") String tipoProtocolo,
	    @WebParam(name = "origemProtocolo", targetNamespace = "") String origemProtocolo,
	    @WebParam(name = "quantidade", targetNamespace = "") int quantidade);

}
